var myQuestion = [
  {
    id: "Question 1",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "a",
  },
  {
    id: "Question 2",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "b",
  },
  {
    id: "Question 3",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "c",
  },
  {
    id: "Question 4",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "b",
  },
  {
    id: "Question 5",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "d",
  },
  {
    id: "Question 6",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "a",
  },
  {
    id: "Question 7",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "a",
  },
  {
    id: "Question 8",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "b",
  },
  {
    id: "Question 9",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "c",
  },
  {
    id: "Question 10",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "d",
  },
  {
    id: "Question 11",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "a",
  },
  {
    id: "Question 12",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "b",
  },
  {
    id: "Question 13",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "c",
  },
  {
    id: "Question 14",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "b",
  },
  {
    id: "Question 15",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "d",
  },
  {
    id: "Question 16",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "a",
  },
  {
    id: "Question 17",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "a",
  },
  {
    id: "Question 18",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "b",
  },
  {
    id: "Question 19",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "c",
  },
  {
    id: "Question 20",
    text: "This is sample question having answers listed below",
    a: "option a",
    b: "option b",
    c: "option c",
    d: "option d",
    answer: "d",
  },
];
